version: "3.8"

services:
  database:
    container_name: database
    image: postgres:13.3
    environment:
      POSTGRES_DB: "shmogwarts"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "1234"
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
  php:
    container_name: php
    build:
      context: ./docker/php
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/symfony_docker
    depends_on:
      - database
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./app:/var/www/symfony_docker
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database