##Берем родительский образ Nginx
#FROM nginx:mainline-alpine
## Открываем 80 порт
#EXPOSE 81
##Подменяем конфиг Nginx conf.d в контейнере на custom.conf
#COPY default.conf /etc/nginx/conf.d
##Копируем содержимое www в /var/www
#COPY ./www /var/www
##Запускаем Nginx как процесс.
#CMD ["nginx", "-g", "daemon off;"]

